theme: jekyll-theme-architect
title: StudioX ACES Documentation
url: https://sharktacos.github.io/OpenColorIO-configs/
show_downloads: true
description: ACES OpenColorIO configs for CG Animation and VFX studio pipelines
