theme: jekyll-theme-minimal
theme_color:           rgb(8,46,57)
title: StudioX Color Management Documentation
description:           >
  ACES OpenColorIO configs for ANM and VFX pipelines
tagline: StudioX OCIO configs
logo: /docs/img/studioX.png

sidebar:
  nav: "docs"
  

defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"

menu:
  - title: Maya
    url: /docs/Maya.md
  - title: Documentation
    url: /docs/
  - title: About
    url: /about/

