theme: jekyll-theme-minimal
title: StudioX Color Management Docs
description:           >
  ACES OpenColorIO configs for ANM and VFX pipelines
tagline: StudioX OCIO configs
logo: /docs/img/studioX.png

menu:
  - title: Maya
    url: /docs/Maya.md
  - title: Documentation
    url: /docs/
  - title: About
    url: /about/

